name = "Havoc Realms S3"
author = "minecraftbossdj, NullHarp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1e51ec54d1bb5cde08c56666dd6b7e3411a67586c3eeb52f95345de5ed705b3"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
